config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets or /tweets.json
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all.order(created_at: :desc)
    not_include_user = user_signed_in? ? current_user.id : nil
    @users = User.where.not(id: not_include_user).order(created_at: :desc)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.user.id != current_user.id 
        flash.now[:alert] = "You can only edit your own tweets"
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { message: "You can't edit this tweet." }, status: :unprocessable_entity }
      else
        if @tweet.update(tweet_params)
          puts "ddfsaf"
          format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
          format.json { render :show, status: :ok, location: @tweet }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @tweet.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: 'navbar-item' do %>
          <h1 class="title is-5">Twitter</h1>
        <% end %>
        <div class="navbar-burguer burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <%= link_to "New Tweet", new_tweet_path, class: "button is-light" %>
              <% if user_signed_in? %>
                <%= link_to current_user.name, edit_user_registration_path, class: 'button is-info' %>
                <%= link_to 'Logout', destroy_user_session_path, class: 'button is-danger', data: { turbo_method: :delete, turbo_confirm: "You want to sign out?"  } %>
              <% end %>
              <% if !user_signed_in? %>
                <%= link_to 'Sign up', new_user_registration_path, class: 'button is-primary' %>
                <%= link_to 'Login', new_user_session_path, class: 'button is-light' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notifcation">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notifcation">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
    <article class="media box">
      <figure class="media-left">
        <p class="image is-64x64">
          <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <%= render 'form' %>
        </div>
      </div>
    </article>
  <% end %>
  <% tweets.each do |tweet| %>
    <div class="box">
      <div class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= tweet.user.name %></strong> <br/>
            <small>@<%= tweet.user.username %></small> <br />
            <p><%= tweet.tweet %></p>
          </div>
          <% if user_signed_in? && tweet.user.id == current_user.id %>
            <nav class="level">
              <div class="level-left is-mobile">
                <%= link_to tweet, class: "level-item" do %>
                  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to tweet, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this tweet?" } do %>
                  <span class="icon"><i class="fa fa-trash" aria-hidden="true"></i></span>
                <% end %>
              </div>
            </nav>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :tweet, autofocus: true, label: "Tweet about it", input_html: { class: "textarea" }, wrapper: false, label_html: { class: 'label' }, placeholder: "Compose a new tweet..." %>
    </div>
  </div>
  <%= f.button :submit, class: 'button is-info' %>
<% end %>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">
      Profile
    </p>
    <div class="panel-block">
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= current_user.name %></strong><br/>
              <small>@<%= current_user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Tweets</p>
            <p class="title is-6"> <%= current_user.tweets.count %> </p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6">123</p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Follower</p>
            <p class="title is-6">234K</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/tweets/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Trends</p>
    <div class="panel-block">
      <p>trend 1</p>
    </div>
    <div class="panel-block">
      <p>trend 2</p>
    </div>
    <div class="panel-block">
      <p>trend 3</p>
    </div>
    <div class="panel-block">
      <p>trend 4</p>
    </div>
  </nav>
</div>

app/views/tweets/_tweet.html.erb
<div class="box">
  <div class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <strong><%= tweet.user.name %></strong> <br/>
        <small>@<%= tweet.user.username %></small> <br />
        <p><%= tweet.tweet %></p>
      </div>
      <% if user_signed_in? && tweet.user.id == current_user.id %>
        <nav class="level">
          <div class="level-left is-mobile">
            <%= link_to tweet, class: "level-item" do %>
              <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
              <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to tweet, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this tweet?" } do %>
              <span class="icon"><i class="fa fa-trash" aria-hidden="true"></i></span>
            <% end %>
          </div>
        </nav>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/_who-to-follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">Who to follow</p>
    <% @users.each do |user| %>
      <div class="panel-block">
        <article class="media">
          <figure class="media-left">
            <p class="image is-32x32">
              <%= gravatar_image_tag(user.email, size: 32, alt: user.name) %>
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong><%= user.name %> </strong> <small>@<%= user.username %></small>
                <br>
              </p>
            </div>
          </div>
        </article>
      </div>
    <% end %>
  </nav>
</div>

app/views/tweets/edit.html.erb
<section class="section pt-5">
  <div class="container">
    <h1 class="title">Editing tweet</h1>
    <%= render "form", tweet: @tweet %>
    <br>
    <div>
      <%= link_to "Show this tweet", @tweet %> |
      <%= link_to "Back to tweets", tweets_path %>
    </div>
  </div>
</section>

app/views/tweets/index.html.erb
<section class="section pt-5">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>
      <%= render 'feed', tweets: @tweets %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<section class="section pt-5">
  <div class="container">
    <h1 class="title">New tweet</h1>
    <%= render "form", tweet: @tweet %>
    <br>
    <div>
      <%= link_to "Back to home", root_path %>
    </div>
  </div>
</section>

app/views/tweets/show.html.erb
<section class="section">
  <div class="container">
    <div class="pb-5">
      <%= link_to "Back to home", root_path %>
    </div>
    <%= render @tweet %>
  </div>
</section>